- vector/src/main/java/im/vector/activity/VectorRoomActivity.java
- vector/src/main/java/im/vector/adapters/VectorMessagesAdapter.java
- vector/src/main/java/im/vector/fragments/VectorRoomSettingsFragment.java
L'encryption est indispensable ds tchap. Cependant nous souhaitons modifier l'ux et ameliorer la gestion des devices (on ne sait pas encore comment). En attendant, pour pouvoir proposer l'encryption sans perturber l'utilisateur non averti, l'idee est de mettre les alertes en sourdine, quitte à valider automatiquement les devices inconnus.
> Retrait temporaire des alertes sur l'encryption

- vector/src/main/java/im/vector/activity/VectorHomeActivity.java
- vector/src/main/java/im/vector/util/RoomUtils.java
- vector/src/main/res/menu/bottom_navigation_main.xml
- vector/src/main/res/menu/vector_home_room_settings.xml
Dans un but de simplification les ecrans home et favoris disparaissent (pas exclu que favoris réapparaissent sous une forme ou sous une autre).
Passage en Francais de l'item de création de raccourci (il faudrait creer une string).
Enfin, puisque pour l'instant les communautés ne sont pas integrées, nous gardons l'icone groupe tel qu'il etait avant.
> Masquage des menus home et favoris.

- vector/src/main/java/im/vector/activity/CommonActivityUtils.java
- vector/src/main/java/im/vector/activity/LoginActivity.java
- vector/src/main/java/im/vector/activity/VectorRoomCreationActivity.java
- vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java
- vector/src/main/java/im/vector/adapters/ParticipantAdapterItem.java
- vector/src/main/java/im/vector/adapters/PeopleAdapter.java
- vector/src/main/java/im/vector/adapters/VectorParticipantsAdapter.java
- vector/src/main/java/im/vector/fragments/PeopleFragment.java
- vector/src/main/java/im/vector/util/DinsicUtils.java
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
Quelques modifications liées à l'affichage des contacts locaux:
Les contacts sans emails sont quand même montrés mais on ne peut pas les inviter (l'idée ds les sprints à venir c'est de pouvoir completer à la volée l'email et/ou d'inviter par sms. D'ne maniere général on cherche à augmenter la viralité)
Lorsqu'on invite un externe non encore enrolé il y a un msg d'avertissement (car il y a une certaine responsabilité àprendre)
L'ordre d'affichage des contacts locaux est modifié: d'abord les contacts matrix et les contacts en gouv.fr, ensuite les autres, qui apparaissent en grisé (dans une logique telegram)
Une modification dans la recherche d'une direct room avant creation, pour ne pas recreer une room dans le cas d'un contact non encore matrix mais déja invité dans une room
> Dinsic localcontact

- vector/src/main/java/im/vector/gcm/GcmRegistrationManager.java
- vector/src/main/java/im/vector/util/PreferencesManager.java
Fdroid non gcm notifications works well with our special secured mobile phone if we set short delays and autostart on reboot
> Set default values for fdroid non gcm notification mechanism

- vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java
Bug on Tchap when you try to invite someone in a room by typing his id or email, the email gov verification crash (null pointer).
> Tchap Bug (not Riot) when you invite someone by typing his id or email

- vector/src/main/res/layout/activity_vector_login.xml
On the login screen, the email field indicated "E-mail or username" while the username didn't work. The placeholder should only mention the email.
> DINSIC : Login screen update email placeholder

- vector/src/main/java/im/vector/activity/VectorRoomCreationActivity.java
- vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java
- vector/src/main/java/im/vector/fragments/ContactFragment.java
- vector/src/main/java/im/vector/fragments/PeopleFragment.java
- vector/src/main/res/layout/fragment_people.xml
Refers to https://github.com/dinsic-pim/riot-android/issues/44
Avoid cross invitations and creating multiple direct chats for the same 2 users
- join the room if an invitation is pending and don't create a new direct chat
> Handle pending invitation before creating new direct chat

- vector/build.gradle
- vector/src/main/res/layout/vector_activity_splash.xml
Remove dependency to droidsonroids (including a native library) to display (only) a static splash screen image.
> Remove dependency to droidsonroids (static splash image)

- vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
- handle room alias already taken
- handle room alias with invalid characters
- handle federation denied error
Related to  #249.
> Room creation: Do not prompt the user if the alias is already used

- vector/src/main/AndroidManifest.xml
- vector/src/main/java/fr/gouv/tchap/activity/AccessibilityServiceDetectionActivity.java
- vector/src/main/java/fr/gouv/tchap/activity/NotificationListenerDetectionActivity.java
- vector/src/main/java/fr/gouv/tchap/util/LiveSecurityChecks.java
- vector/src/main/java/im/vector/activity/VectorHomeActivity.java
- vector/src/main/java/im/vector/activity/VectorRoomActivity.java
- vector/src/main/java/im/vector/activity/VectorRoomDetailsActivity.java
- vector/src/main/java/im/vector/activity/VectorSharedFilesActivity.java
- vector/src/main/java/im/vector/util/PreferencesManager.java
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
- vector/src/main/res/values/styles.xml
- vector/src/main/res/xml/vector_settings_preferences.xml
While they can be legitimate to assist users with specific accessibility devices, accessibility services are also known to be used by malwares ([https://thehackernews.com/2017/11/android-accessibility-services.html](https://thehackernews.com/2017/11/android-accessibility-services.html)).
This patch permits to detect such services when the application is launched and if such service is detected, it informs the user, and asks him (only once) if application should start or not.
> Detect accessibility service

- vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java
- vector/src/main/res/layout/fragment_tchap_first_forgotten_password.xml
@bmarty I tested your PR in real life, it works well. I just applied some few improvements
that you can review by this PR.
Note: I don't understand why we implement "onBackPressed()" whereas `KeyEvent.KEYCODE_BACK` is handled by "boolean onKeyDown(int keyCode, KeyEvent event)". We should keep only one of them...
> Update after testing in real life Forgotten password screens

- vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
- when creating a public room, set the history visibility to world_readable
Related to  #262
> Public rooms: turn on the preview by default

- vector/src/main/java/im/vector/adapters/VectorMessagesAdapterHelper.java
- vector/src/main/res/layout/adapter_item_vector_message_image_video.xml
Remove temporarily the vector graphic use to render sticker description
because this item is not supported in some  Android 4.
Note sticker are not supported for the moment
See details in the initial PR #319
> Fix crash with media (images/videos) on Android 4.x

- vector/src/main/java/im/vector/activity/NotificationPrivacyActivity.java
- vector/src/main/java/im/vector/push/PushManager.java
- vector/src/main/java/im/vector/util/PreferencesManager.java
- vector/src/main/res/layout/activity_notification_privacy.xml
We fallback to the LOW_DETAIL mode by default,
and reset the "IgnoreBatteryOptimization" to invite again the user to use the NORMAL mode on VectorHomeActivity resume.
#466
> Notification Privacy: the REDUCED privacy mode is removed in Tchap.

- vector/src/main/java/im/vector/activity/VectorHomeActivity.java
The last message handling of the room summaries has been modified by PR #490 (available since version 49)
This change requires a clear of the existing cache if any.
> Force a clear cache on the application update

- vector/build.gradle
Required by the Google Play 64-bit requirement:
Note: the APK size is growing up due to this change. The version Tchap-agent without voip grows up from 12.2 MB to 14.6 MB.
The included libraries in this APK:
> include 64bits version of the libraries in the APK

- vector/src/main/java/im/vector/notifications/NotificationUtils.kt
- vector/src/main/java/im/vector/services/EventStreamService.java
The notifications are not displayed if all the following conditions are met:
- F-droid without VoIP flavor (without the WAKE_LOCK permission)
- application is running in background
- option "Turn screen on for 3 seconds" is set
This pull request catches the exception thrown by the `newWakeLock` call ASAP which permits the notification to appear.
> Fix notification problem when the WAKE_LOCK permission is not granted

- vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java
- vector/src/test/java/fr/gouv/tchap/util/DinsicUtilsTest.kt
The crash is observed when the user id contains empty string between '-' character.
#560
> BugFix - App crashes during `computeDisplayNameFromUserId`

- vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
- vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java
- vector/src/main/java/fr/gouv/tchap/util/DinumUtils.kt
- vector/src/main/java/im/vector/fragments/VectorRoomDetailsMembersFragment.java
- vector/src/main/java/im/vector/fragments/VectorRoomSettingsFragment.java
Target = protecteed
- Hide the invite by email which is not supported in Tchap-secure
- Hide the room access rules settings. There is no external users in Tchap-secure, all the room are `restricted` or `direct` for the moment. This state event is handled automatically at the room creation on server side
> Clean the Tchap-secure application

- vector/src/appfdroid/java/im/vector/push/fcm/NotificationTroubleshootTestManagerFactory.kt
- vector/src/main/java/im/vector/util/PreferencesManager.java
Contrary to Riot, the default mode will be FDROID_BACKGROUND_SYNC_MODE_FOR_REALTIME because it was the actual mode before the multiple Fdroid sync background modes was introduced. We don't want to change implicitly the notification handling on application update.
> Fdroid: force the realtime sync mode by default

- vector/src/main/java/im/vector/notifications/NotificationDrawerManager.kt
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
- Do not show a summary when only one notification is presented
- Display the event body in the summary when only one message is pending for a room
- Remove the "domain" of the sender display name
- Handle properly direct room
> Improve the notifications display on devices running API level < 24

- vector/src/main/java/im/vector/activity/LockScreenActivity.java
- vector/src/main/java/im/vector/activity/VectorRoomActivity.java
TODO: fix the rendering of the error message in the toast displayed on devices running API < 24
> Bug Fix - Quick Reply: Handle correctly the failure on unknown devices

- vector/src/main/java/im/vector/adapters/VectorMessagesAdapter.java
- vector/src/main/java/im/vector/adapters/VectorMessagesAdapterHelper.java
#594
We handle here correctly the case where the keys are requested again by the user.
During tests, we observed another case where the keys are requested automatically when the message is rendered for the first time (this case is fixed too)
> Bug Fix - Some messages are stuck on decryption failure whereas the keys have been shared

- vector/src/main/java/im/vector/notifications/NotificationDrawerManager.kt
This was due to our previous changes to improve notifications on devices running API level < 24.
Indeed the summary was preventing the user from seeing the messages when only one room is notified on devices running API level < 24. Our first correction broke the notification sound on all devices when only one notification is displayed.
We apply here another patch to display the unique summary line, instead of "1 Notification" on devices running API level < 24. And keep the existing code for other devices
> Bug Fix: The sound is missing on some notifications

- vector/src/main/java/im/vector/notifications/NotificationDrawerManager.kt
This was due to the call of refreshNotificationDrawer in iconLoader callback.
This call refreshes the SummaryListNotification without sound because then `hasNewEvent` is false...
I decided to ignore this refresh for the moment to keep the sound
> Bug Fix: The notification sound is missing for the first one after backgrounding the app

- vector/src/agent/AndroidManifest.xml
- vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java
- vector/src/main/java/im/vector/LoginHandler.java
- vector/src/main/java/im/vector/activity/VectorUniversalLinkActivity.java
- vector/src/main/java/im/vector/util/BugReporter.java
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
- vector/src/preprod/AndroidManifest.xml
- vector/src/protecteed/AndroidManifest.xml
- Universal links: update the listed url paths to limit them to the supported ones
- Support now the email validation process with Synapse (registration and password_reset only)
- Pursue the account creation (or password reset) in Login Activity
- TchapLoginActivity: Do not stop loading wheel on registration flow update - the registration is still in progress (for Tchap)
> Fix email validation catch up:

- vector/src/main/java/im/vector/activity/VectorRoomActivity.java
The icon is displayed when there are 2 joined members, or more than 3 members (joined and invited members)
#615
> VoIP hide the call icon when the user is the only one joined member, and there is no more than 1 invite

- TCHAP_CHANGES.rst
- vector/src/main/java/im/vector/services/EventStreamServiceX.kt
Force a restart if the currentSyncToken is null whereas the store is ready.
#639
> Bug Fix: [Expired Account] Tchap is stuck on the splash screen whereas the account is renewed

- TCHAP_CHANGES.rst
- vector/src/main/java/fr/gouv/tchap/activity/TchapRoomAccessByLinkActivity.kt
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
In case of a private room opened to the external users, we have to notify the admins when they turn on the access by link that the external users will still require an invite to join.
#645
> [Room access] Improve the wording related to the room link access

- vector/src/main/res/layout/adapter_item_tchap_media_scan.xml
> Attachments: an empty bubble is displayed for the infected attachments

- TCHAP_CHANGES.rst
- vector/src/main/java/im/vector/activity/VectorHomeActivity.java
This will fix:
- Crash: on new favorite message #670
- Crash: java.lang.NullPointerException at org.matrix.androidsdk.data.RoomAccountData.handleEvent #671
> Force a cache clearing to force an update of the stored RoomAccountData

- vector/src/main/AndroidManifest.xml
Apps that target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files.
TODO use Scoped Storage
#683
> Bug Fix: [Android 10] permission denied to open a pdf

- TCHAP_CHANGES.rst
- vector/src/main/java/im/vector/dialogs/ExportKeysDialog.kt
- vector/src/main/res/values-fr/strings.xml
- vector/src/main/res/values/strings.xml
#712 
here is the updated dialog:
> Define a minimum size for the passphrase used to encrypt the exported keys file
