dinsic-pim/tchap-android

vector/src/main/java/im/vector/RegistrationManager.java, vector/src/main/java/im/vector/receiver/VectorRegistrationReceiver.java
https://chat.[i,a,e].tchap.rie.gouv.fr/#/register...
=> Registration: Update the next link base to consider the right URL shape:

vector/src/main/java/im/vector/activity/VectorHomeActivity.java
https://github.com/dinsic-pim/riot-android/issues/36
=> DINSIC sp1.8 : onFabClick invite people to new room

vector/src/main/java/im/vector/util/RoomUtils.java, vector/src/main/res/menu/vector_home_room_settings.xml, vector/src/main/res/values-fr-rCA/strings.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
https://github.com/dinsic-pim/riot-android/issues/35
This PR only concerns the case of "1- Remove the option ""discussion directe" from the context menu".
The case "2- It is not possible to add member in a Dialogue (Direct chat)" will be handle in an other PR.
=> DINSIC_sp1.7 : Fab delete DirectChat option on Room List Context Menu

vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.java, vector/src/main/java/im/vector/util/PreferencesManager.java
1 - disable delete email from user account
2 - suppress add email button
=> DINSIC_sp1.14 : user settings email

vector/src/main/res/values-fr-rCA/strings.xml
Delete string from fr-rCA because of Gradle issue
=> DINSIC_sp1.7 : Add i18n

vector/src/main/java/im/vector/activity/RoomDirectoryPickerActivity.java, vector/src/main/java/im/vector/fragments/RoomsFragment.java, vector/src/main/java/im/vector/util/RoomDirectoryData.java, vector/src/main/res/values/donottranslate.xml
matrix public room are inaccessibles, so make them unseen
Related to issue #28
=> make matrix public room unseen

vector/src/main/res/layout/activity_vector_login.xml
On the login screen, open the specific keyboard for emails rather than the standard keyboard
=> Login screen : open email keyboard

vector/src/main/java/fr/gouv/tchap/sdk/rest/api/TchapApi.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapRestClient.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/model/Platform.java, vector/src/main/java/im/vector/activity/LoginActivity.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorUniversalLinkActivity.java, vector/src/main/java/im/vector/adapters/ContactAdapter.java, vector/src/main/java/im/vector/fragments/ContactFragment.java, vector/src/main/java/im/vector/receiver/VectorRegistrationReceiver.java, vector/src/main/res/values/donottranslate.xml
Use the new API `GET https://$identity_server/_matrix/identity/api/v1/discover_urls`
to retrieve the tchap platform according to the entered email.
#43
=> Registration: Improve the servers selection

vector/src/main/java/im/vector/activity/LoginActivity.java
=> Bug Fix: Registration: the email field is changed on app resume

vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/activity/LoginActivity.java, vector/src/main/java/im/vector/receiver/VectorRegistrationReceiver.java, vector/src/main/res/values/donottranslate.xml
Fix several issues in the Login activity related to the server configuration. This configuration depends on the provided email. There is no config by default.
=> Update the known identity server names

vector/src/main/java/im/vector/activity/VectorRoomActivity.java
Issue #79 correction.Crash sometime when try to access public rooms. Due to a nullpointerexception.
=> Issue #79 correction.Crash sometime when try to access public rooms

vector/src/main/java/im/vector/activity/LoginActivity.java, vector/src/main/res/layout/activity_vector_login.xml
- force the mxID on the client side until the server is able to handle it
- force the user display name too
This changes must be reverted when the server will handle the mxID and the display name
=> The MXID is based on the 3PID

vector/src/main/java/im/vector/activity/LoginActivity.java
Bug fix: when click to register then login button, you can not go back to register again (issue #96)
=> reactivate register button when click to login button

vector/src/main/java/im/vector/fragments/ContactFragment.java
=> Bug Fix: Hide the current user from the Contacts list

vector/src/main/java/im/vector/activity/VectorRoomCreationActivity.java, vector/src/main/java/im/vector/util/VectorUtils.java
https://github.com/dinsic-pim/riot-android/issues/45
=> Open and name a direct chat that has been left

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/res/values-fr/strings.xml
https://github.com/dinsic-pim/riot-android/issues/69
=> Invite left members

vector/src/main/java/im/vector/util/SlashComandsParser.java
- Disable /nick cmd: the display name is fixed.
- Disable /invite cmd in direct chats.
=> Update IRC command handling:

vector/src/main/java/im/vector/util/SlashComandsParser.java
Related to https://github.com/dinsic-pim/riot-android/pull/106
=> Disable /invite cmd if the current user belongs to the E-platform.

vector/src/main/res/values-fr/strings.xml
https://github.com/dinsic-pim/riot-android/issues/135
=> Replace "salon" by "discussion"

vector/src/main/java/im/vector/adapters/RoomAdapter.java
https://github.com/dinsic-pim/riot-android/issues/125
=> External users can't access to public rooms

vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.java, vector/src/main/res/xml/vector_settings_preferences.xml
https://github.com/dinsic-pim/riot-android/issues/134
=> Do not allow update of the user's display name

vector/src/main/res/values-fr/strings.xml
https://github.com/dinsic-pim/riot-android/issues/130
=> Update room terminology

vector/src/main/java/fr/gouv/tchap/fragments/ContactFragment.java
https://github.com/dinsic-pim/riot-android/issues/132
=> Hide no tchap users on contacts screen

vector/src/main/AndroidManifest.xml, vector/src/main/java/fr/gouv/tchap/adapters/ContactAdapter.java, vector/src/main/java/fr/gouv/tchap/fragments/ContactFragment.java, vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorRoomCreationActivity.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/java/im/vector/adapters/VectorParticipantsAdapter.java, vector/src/main/java/im/vector/fragments/HomeFragment.java, vector/src/main/res/layout/activity_vector_invite_members.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
https://github.com/dinsic-pim/riot-android/issues/131
https://github.com/dinsic-pim/riot-android/issues/133
=> Change room creation option

vector/src/main/java/fr/gouv/tchap/media/MediaScanDao.java, vector/src/main/java/fr/gouv/tchap/media/MediaScanManager.java, vector/src/main/java/im/vector/adapters/VectorMessagesAdapter.java, vector/src/main/java/im/vector/adapters/VectorMessagesAdapterHelper.java, vector/src/main/java/im/vector/fragments/VectorMessageListFragment.java, vector/src/main/res/layout/adapter_item_vector_message_image_video.xml
=> Antivirus: Add MediaScan in the attachments handling

vector/src/main/AndroidManifest.xml, vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/res/layout/activity_tchap_room_creation.xml, vector/src/main/res/menu/tchap_room_creation_menu.xml, vector/src/main/res/values-fr/strings.xml
Design of the first screen for room creation.
The first screen is used to enter the avatar, the name of the discussion, and the public / private type.
Related to : #127
=> Tchap room creation v1 : add new screen

vector/build.gradle, vector/src/main/res/drawable-mdpi/avatar_mask_hexagon.xml, vector/src/main/res/layout/activity_tchap_room_creation.xml, vector/src/main/res/values-fr/strings.xml
=> Tchap room creation : hexagon shape

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
https://github.com/dinsic-pim/riot-android/issues/127
=> Room creation : Add alert dialog to prompt user about error avatar loading

vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.java, vector/src/main/java/im/vector/util/VectorUtils.java, vector/src/main/res/layout/activity_home.xml, vector/src/main/res/layout/tab_icon.xml, vector/src/main/res/layout/vector_room_header.xml, vector/src/main/res/values/colors.xml, vector/src/main/res/xml/vector_settings_preferences.xml
Update Tchap colors
Disable themes settings
Related to  #178
=> Theme: Update Tchap colors

vector/src/main/java/fr/gouv/tchap/fragments/ContactFragment.java, vector/src/main/java/im/vector/adapters/VectorParticipantsAdapter.java
=> Bug Fix - Some non-tchap users are displayed in the Contacts list

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
- handle room privacy
- handle room alias when room is public
Related to #127
=> Room creation - first steps: Avatar, Name, Privacy and Participants #127

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/activity/VectorRoomCreationActivity.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/java/im/vector/fragments/VectorRoomDetailsMembersFragment.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Invitation des contacts: Check whether the contact can register before inviting him

vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/res/layout/activity_home.xml, vector/src/main/res/layout/vector_home_menu_header.xml, vector/src/main/res/menu/vector_home_sliding_menu.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/colors.xml, vector/src/main/res/values/dimens.xml, vector/src/main/res/values/strings.xml, vector/src/main/res/values/styles.xml
=> Burger menu: update design #191

vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java
#223 focus on search field when click on search icon
=> get focus when click on search icon

vector/src/main/java/im/vector/fragments/VectorRoomDetailsMembersFragment.java
=> tchap_only users when invite to a room

vector/src/main/java/im/vector/activity/VectorHomeActivity.java
=> fix bug when select contact in burger menu

vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/res/menu/vector_home_sliding_menu.xml
=> hide privacy policy, keep only cgu

vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.java, vector/src/main/res/xml/vector_settings_preferences.xml
=> hide several parameters

vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/res/menu/vector_home_sliding_menu.xml
=> hide bug report function

vector/src/main/java/im/vector/util/VectorUtils.java
=> moove informational links to tchap platform

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java
issue #219 
when click on a contact, the dialog is open twice
=> correct a bug that  open a direct tchat twice

vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/activity/CommonActivityUtils.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/adapters/VectorMessagesAdapter.java, vector/src/main/java/im/vector/fragments/VectorMessageListFragment.java, vector/src/main/java/im/vector/receiver/VectorUniversalLinkReceiver.java, vector/src/main/java/im/vector/util/VectorUtils.java, vector/src/main/java/im/vector/view/PillView.java, vector/src/main/res/xml/vector_room_settings_preferences.xml
=> Disable permalink, remove matrix.to handling

vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java, vector/src/main/java/fr/gouv/tchap/fragments/TchapRoomsFragment.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/res/layout/activity_home.xml, vector/src/main/res/layout/fragment_people_and_invite.xml
#240 Fix the crash and improve sliding consecutive to invite button introduction
=> Dinsic sp5 fix crash onchange tab

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/CommonActivityUtils.java, vector/src/main/java/im/vector/activity/VectorMemberDetailsActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/adapters/ParticipantAdapterItem.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Contacts: new direct chat creation

vector/src/main/java/fr/gouv/tchap/fragments/TchapRoomsFragment.java, vector/src/main/java/im/vector/fragments/RoomsFragment.java
=> Discussion: some discussions are missing in the conversations list

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java
After joining the room, do not close the app on back-press.
Related to  #255.
=> Select back on a recently joined room make the user leave the app.

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java
=> Unable to accept an invitation without giving consent

vector/src/main/java/im/vector/adapters/RoomViewHolder.java, vector/src/main/java/im/vector/util/RoomUtils.java, vector/src/main/res/layout/adapter_item_direct_room_view.xml, vector/src/main/res/layout/adapter_item_room_view.xml, vector/src/main/res/values/colors.xml
- Update the design
- Hide sender name if the last message starts with his display name
#258
=> Room summary : sender display name is wrong.

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/layout/fragment_tchap_first_login.xml, vector/src/main/res/layout/fragment_tchap_first_register.xml
=> Authentication screen: Improve keyboard handling

vector/src/main/java/fr/gouv/tchap/adapters/TchapContactAdapter.java, vector/src/main/java/im/vector/adapters/ParticipantAdapterItem.java, vector/src/main/java/im/vector/adapters/VectorParticipantsAdapter.java, vector/src/main/java/im/vector/adapters/VectorRoomDetailsMembersAdapter.java, vector/src/main/res/layout/adapter_item_vector_add_participants.xml
- center vertically the display name (by removing the status label)
- add the green light for online users
- add user's domain for the local contact by considering his email
Related to  #261
=> Contacts picker: Improve Tchap contacts display

vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java
=> Hide the "inviter des contacts dans Tchap" button

vector/src/main/java/fr/gouv/tchap/adapters/TchapRoomAdapter.java
...in the rooms search result
Related to #279
=> Some discussions are displayed like a salon (and conversely)... 

vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java
=> Display the discussions invites in the Conversations tab

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java
=> Creation of an infinity of rooms

vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java
=> Bug Fix: Unable to give my consent when I reject a room invite

vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Wording when sign in

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
=> Room creation: highlight the caution for public rooms

vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java, vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorMemberDetailsActivity.java, vector/src/main/java/im/vector/util/VectorUtils.java
#309
Note: fix here a bug when leave contact tab and come back, with an active filter (inspired by PR #306)
=> Bug Fix: The display name of some users is missing

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
Fix an infinite loading wheel without feedback
=> Handle correctly unauthorized email during registration

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/layout/activity_tchap_login.xml, vector/src/main/res/layout/fragment_tchap_first_forgotten_password.xml, vector/src/main/res/layout/fragment_tchap_first_login.xml, vector/src/main/res/layout/fragment_tchap_message_button.xml, vector/src/main/res/values/styles.xml
Contains the 3 screens displayed when user click on "Forgotten password" on the login screen
Not tested yet in real life (worflow tested in debug mode), but opening PR for the review
=> Forgotten password screens

vector/src/main/java/fr/gouv/tchap/activity/TchapPublicRoomSelectionActivity.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/res/drawable-xhdpi/tchap_search_bar_style.xml, vector/src/main/res/layout/activity_tchap_public_room.xml, vector/src/main/res/layout/activity_vector_invite_members.xml
=> Update the search bar display

vector/src/main/java/im/vector/activity/VectorHomeActivity.java
=> Application crash during logout

vector/src/main/java/fr/gouv/tchap/activity/TchapPublicRoomSelectionActivity.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/java/im/vector/adapters/VectorMessagesAdapter.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
- get focus when click on search icon in public rooms and invite in a room
- change "rejoindre la conversation" by "rejoindre" when go to a room, it was to big for the button
- put expand/collapse in french
=> Dinsic sp6 clickonsearchiconregression

vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/activity/SelectPictureActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/withVoip/AndroidManifest.xml, vector/src/withoutVoip/AndroidManifest.xml
Reverts dinsic-pim/riot-android#335
=> Revert "Fix regression introduced by the camera handling changes"

vector/src/main/java/im/vector/activity/VectorHomeActivity.java
Only the Conversation tab has an unread badge.
=> Bug Fix - An unread badge is displayed on Contact tab by mistake

vector/src/main/java/im/vector/adapters/VectorParticipantsAdapter.java
=> Search in invite contacts screen : do not display user directory

vector/src/main/java/im/vector/activity/VectorRoomActivity.java
=> Bug Fix Multiple invites sent when I try to start a conversation

vector/src/main/java/im/vector/activity/CommonActivityUtils.java, vector/src/main/java/im/vector/activity/SelectPictureActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java
Reverts dinsic-pim/riot-android#338
=> Ask permission to take photo only if the Camera permission is present in the Manifest.

vector/src/main/java/fr/gouv/tchap/fragments/TchapRoomsFragment.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java
(kicked or banned). 
Related to #349
=> After a user is excluded from a room, the application crashes when he wants to display it.

vector/src/main/res/layout/dialog_export_e2e_keys.xml, vector/src/main/res/layout/dialog_import_e2e_keys.xml
=> Settings - Keys export/import dialog: the button label is not readable

vector/src/main/java/fr/gouv/tchap/activity/TchapPublicRoomSelectionActivity.java, vector/src/main/java/fr/gouv/tchap/adapters/TchapPublicRoomAdapter.java, vector/src/main/java/fr/gouv/tchap/fragments/TchapPublicRoomsFragment.java, vector/src/main/java/im/vector/adapters/AbsAdapter.java
=> Public Rooms: the loading wheel is missing 

vector/src/main/java/im/vector/fragments/VectorRoomSettingsFragment.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml, vector/src/main/res/xml/vector_room_settings_preferences.xml
- The encryption is then enabled by default
- The new members can access only on invite
#368
=> A public room may become private

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/res/layout/activity_tchap_room_creation.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
When the user creates a public room, he has to specify if the room is federated or not.
#129
=> Public rooms: configure the federation

vector/build.gradle, vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorMemberDetailsActivity.java, vector/src/main/java/im/vector/fragments/VectorRoomSettingsFragment.java, vector/src/test/java/fr/gouv/tchap/util/DinsicUtilsTest.kt
- Improve the display name built from the user id: Capitalize each component when the name contains "-"
#368
=> Bug Fix - Room Settings: the matrix id is displayed for the banned user.

vector/src/main/java/im/vector/VectorApp.java, vector/src/main/java/im/vector/activity/VectorMemberDetailsActivity.java, vector/src/main/java/im/vector/fragments/VectorRoomDetailsMembersFragment.java, vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt, vector/src/main/java/im/vector/util/PreferencesManager.java, vector/src/main/java/im/vector/util/SlashCommandsParser.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml, vector/src/main/res/xml/vector_settings_preferences.xml
Require https://github.com/matrix-org/matrix-android-sdk/pull/397, and the last version of the SDK
Fixes #385
=> Add an option to hide user from Directory search

vector/build.gradle, vector/src/agent/AndroidManifest.xml, vector/src/agent/res/values/config.xml, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorUniversalLinkActivity.java, vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt, vector/src/main/java/im/vector/util/BugReporter.java, vector/src/main/java/im/vector/util/PreferencesManager.java, vector/src/main/java/im/vector/util/RageShake.java, vector/src/main/res/menu/vector_home_sliding_menu.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/donottranslate.xml, vector/src/main/res/xml/vector_settings_preferences.xml, vector/src/preprod/AndroidManifest.xml, vector/src/preprod/res/values/config.xml, vector/src/protecteed/AndroidManifest.xml, vector/src/protecteed/res/values/config.xml
=> Enable bug report, and rage shake

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/layout/fragment_tchap_first_register_wait_for_email.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Improve registration process

vector/src/main/java/im/vector/util/VectorUtils.java
+ handle SSL error by notifying the user
=> Update TAC url

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java
Currently the app is stuck on the polling screen (email validation)
=> Bug Fix; move back to the registration screen on registration failure

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/layout/fragment_tchap_first_register_wait_for_email.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Registration: remove the polling mechanism

vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Turn on the option to invite contacts by email

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/KeyRequestHandler.java, vector/src/main/java/im/vector/LoginHandler.java, vector/src/main/java/im/vector/RegistrationManager.java, vector/src/main/res/values-fr/strings.xml
@bmarty: Do you know a better way to get an end-user-visible name than Build.MODEL?
#422
=> Keys sharing: remove the verification option

vector/src/main/java/fr/gouv/tchap/media/MediaScanManager.java, vector/src/main/java/im/vector/adapters/VectorMessagesAdapter.java
=> Bug Fix - Antivirus scan: outgoing attachments are considered infected by mistake

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/util/PermissionsTools.kt
(This permission must not be asked for the target without voip)
=> Fix an unexpected warning when the Camera permission is requested

vector/src/main/AndroidManifest.xml, vector/src/withoutpinning/res/xml/network_security_config.xml, vector/src/withpinning/res/xml/network_security_config.xml
=> Trust the user CAs in apk built without pinning

vector/src/app/java/im/vector/push/fcm/FcmHelper.java, vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
- ensure FCM token is retrieved
#449
=> Bug Fix: FCM service is not working

vector/src/withpinning/res/xml/network_security_config.xml
=> Do not allow system and user certificates in apk built with pinning

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=>  Block invite to a deactivated account user

vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt
=> Parameters: infinite loading wheel on avatar update

vector/src/main/java/im/vector/notifications/NotificationUtils.kt, vector/src/main/java/im/vector/notifications/RoomsNotifications.java
=> Fix issue with badge count (#440)

vector/src/main/java/im/vector/RegistrationManager.java
- Handle correctly unauthorized 3pid error code when the client request an email on token request
=> Bug Fix: Registration - Infinite loading wheel on unauthorized email

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Increase the minimum password length to 8

vector/build.gradle, vector/proguard-rules.pro
Report of https://github.com/vector-im/riot-android/commit/ea00156e2165ea380beffed88d4e70f872dab3fa
- Push tested ok.
- package com.google.firebase.analytics.connector is well removed from APK (checked with Jadx)
=> Exclude Firebase analytics code (#468)

vector/src/app/java/im/vector/push/fcm/VectorFirebaseMessagingService.java, vector/src/main/java/fr/gouv/tchap/activity/TchapDirectRoomDetailsActivity.java, vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/CommonActivityUtils.java, vector/src/main/java/im/vector/activity/LockScreenActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/activity/VectorRoomDetailsActivity.java, vector/src/main/java/im/vector/adapters/RoomViewHolder.java, vector/src/main/java/im/vector/adapters/VectorMemberDetailsAdapter.java, vector/src/main/java/im/vector/adapters/VectorRoomSummaryAdapter.java, vector/src/main/java/im/vector/adapters/VectorRoomsSelectionAdapter.java, vector/src/main/java/im/vector/adapters/VectorSearchFilesListAdapter.java, vector/src/main/java/im/vector/adapters/VectorSearchMessagesListAdapter.java, vector/src/main/java/im/vector/notifications/RoomsNotifications.java, vector/src/main/java/im/vector/services/EventStreamService.java, vector/src/main/java/im/vector/util/RoomUtils.java, vector/src/main/java/im/vector/util/VectorUtils.java, vector/src/withvoip/java/im/vector/activity/JitsiCallActivity.java
=> BugFix: Discussion left by the other member are named "Salon vide"

vector/src/main/java/fr/gouv/tchap/sdk/rest/api/TchapValidityApi.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapValidityRestClient.java, vector/src/main/java/im/vector/Matrix.java, vector/src/main/java/im/vector/activity/SplashActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml, vector/src/main/res/values/theme_light.xml
=> Support the account validity error

vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Prompt external users before displaying their email in user directory

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/api/TchapPasswordPolicyApi.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapPasswordPolicyRestClient.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/model/PasswordPolicy.java
=> Strong pwd policy: check locally the pwd before requesting a new email token

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/res/layout/dialog_invite_by_id.xml, vector/src/main/res/values/strings.xml
=> Allow the user to send a new invite to an external email address

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/fr/gouv/tchap/adapters/TchapContactAdapter.java, vector/src/main/java/fr/gouv/tchap/fragments/TchapContactFragment.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java, vector/src/main/java/im/vector/adapters/ParticipantAdapterItem.java, vector/src/main/java/im/vector/adapters/VectorParticipantsAdapter.java, vector/src/main/java/im/vector/contacts/ContactsManager.java, vector/src/main/java/im/vector/fragments/VectorRoomDetailsMembersFragment.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Room members: invite new members by their email address

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/fr/gouv/tchap/adapters/TchapPublicRoomAdapter.java, vector/src/main/java/fr/gouv/tchap/preference/TchapRoomAvatarPreference.java, vector/src/main/java/fr/gouv/tchap/util/HexagonMaskView.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/activity/VectorRoomDetailsActivity.java, vector/src/main/java/im/vector/adapters/RoomViewHolder.java, vector/src/main/res/layout/activity_tchap_room_creation.xml
- reduce the width of the border for restricted room
- fix the aliasing effect on avatar border
=> Improve the room access marker

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/java/im/vector/contacts/Contact.java
=> Force the email address in lower case in Tchap

vector/src/main/java/im/vector/adapters/AutoCompletedUserAdapter.java
=> Room member completion: Do not display the matrix identifier

vector/src/main/java/im/vector/Matrix.java, vector/src/main/java/im/vector/VectorApp.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
- Bug Fix: Expired account dialog is missing on app restart #521
- Expired account: update the dialog message when on new email has been requested #523
=> Improve expired account handling

vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/notifications/RoomsNotifications.java, vector/src/main/java/im/vector/util/RoomUtils.java, vector/src/main/java/im/vector/util/VectorUtils.java
=> Do not use by default a member avatar for the room avatar

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/res/layout/tchap_room_or_direct_action_bar_custo_layout.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Add room access info in the Room title

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Prompt the user before creating an external account

vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java, vector/src/main/java/im/vector/activity/VectorRoomInviteMembersActivity.java
=> Bug Fix - inviteNoTchapContactsByEmail(): mCount is not decreased if the dialog is dismissed.

vector/build.gradle, vector/src/agent/res/values/config.xml, vector/src/main/java/fr/gouv/tchap/sdk/rest/api/TchapValidityApi.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapPasswordPolicyRestClient.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapRestClient.java, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapValidityRestClient.java, vector/src/main/java/im/vector/Matrix.java, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorUniversalLinkActivity.java, vector/src/main/java/im/vector/receiver/VectorUniversalLinkReceiver.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml, vector/src/preprod/res/values/config.xml, vector/src/protecteed/AndroidManifest.xml, vector/src/protecteed/res/values/config.xml
=> [Account Validity] Handle the renewal url in the Tchap application

vector/src/main/java/fr/gouv/tchap/util/HomeServerConnectionConfigFactory.kt, vector/src/main/java/im/vector/UnrecognizedCertHandler.java, vector/src/main/java/im/vector/store/LoginStorage.java
Indeed some connection parameters (like certificates fingerprints) may have changed
=> Update stored connection configuration before using them

vector/src/main/AndroidManifest.xml, vector/src/main/java/fr/gouv/tchap/activity/TchapLoginActivity.java, vector/src/main/java/fr/gouv/tchap/activity/TchapUnsupportedAndroidVersionActivity.kt, vector/src/main/res/layout/activity_unsupported_android_version.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Limit Tchap to Android 5.0 Lollipop (API 21) and higher

vector/src/main/java/fr/gouv/tchap/util/DinumUtils.kt
=> Improve Kotlin code

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/activity/WidgetActivity.kt, vector/src/main/java/im/vector/adapters/VectorRoomDetailsMembersAdapter.java, vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt, vector/src/main/res/values-fr/strings.xml
=> Order the room members by considering admin(s) first

vector/src/main/java/fr/gouv/tchap/sdk/rest/api/TchapUserInfoApi.kt, vector/src/main/java/fr/gouv/tchap/sdk/rest/client/TchapUserInfoRestClient.kt, vector/src/main/java/fr/gouv/tchap/sdk/rest/model/UserStatusInfo.kt, vector/src/main/java/im/vector/activity/VectorMemberDetailsActivity.java, vector/src/main/java/im/vector/adapters/ParticipantAdapterItem.java, vector/src/main/java/im/vector/adapters/VectorRoomDetailsMembersAdapter.java, vector/src/main/res/layout/activity_tchap_member_details.xml
=> Room members: gray out the expired users

build.gradle, gradle/wrapper/gradle-wrapper.properties, vector/build.gradle
- distribution 5.6.4
- gradle 3.6.3
Patch a failure observed during the soexcluder use
=> Update gradle version

vector/src/agent/java/fr/gouv/tchap/config/TargetConfiguration.kt, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml, vector/src/preprod/java/fr/gouv/tchap/config/TargetConfiguration.kt, vector/src/protecteed/java/fr/gouv/tchap/config/TargetConfiguration.kt
=> Disable the key backup

vector/src/main/java/im/vector/activity/LockScreenActivity.java
Use application context to fix issue related to the special theme of this Activity
Before:
After:
(Do not take care of the Activity under)
=> Fix issue with Toast display

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
=> Room creation: remove special character from the room link

vector/src/main/java/im/vector/adapters/RoomViewHolder.java
=> BugFix: java.lang.NullPointerException (RoomViewHolder.java:197)

vector/src/main/res/values/theme_light.xml
Update SearchView cursor color to white
=> Fix SearchView cursor color

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/util/CallsManager.java
=> [VoIP] The outgoing call failed quietly without reason

vector/src/main/res/layout/activity_home.xml, vector/src/main/res/values/theme_light.xml
Fix edittext hint color regression due to update searchview cursor color.
=> Fix cursor color

vector/src/main/AndroidManifest.xml
Update activity launchmode and taskaffinity following android documentation :
https://developer.android.com/guide/topics/manifest/activity-element#lmode
=> Configure correctly activity launchmode

vector/src/main/java/im/vector/activity/CommonActivityUtils.java
=> fix crash loop back off

.travis.yml, sign_apk.sh, vector/build.gradle
=> Increase targetSdk to 29

vector/src/main/java/im/vector/activity/CommonActivityUtils.java
=> fix restart app feature when access token is invalid

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
=> [Room creation] Do not override the power levels anymore

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/receiver/VectorUniversalLinkReceiver.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Support the preview on shared room link

vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/activity/VectorCallViewActivity.java, vector/src/main/java/im/vector/notifications/NotificationUtils.kt, vector/src/withvoip/AndroidManifest.xml
=> Show call view when screen is locked

vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> [VoIP] Improve the way to call to a new contact

vector/src/main/java/im/vector/util/RoomUtils.java
=> [Notifications] Mention only is not supported in encrypted rooms

vector/src/main/AndroidManifest.xml
=> Multiple activity instances

vector/src/main/java/im/vector/adapters/VectorMessagesAdapterHelper.java
=> [Notifications] Improve mentions handling

TCHAP_CHANGES.rst, vector/src/main/java/im/vector/activity/VectorRoomActivity.java
=> Crash: Activity:im.vector.activity.VectorHomeActivity, Exception: java.lang.NullPointerException

TCHAP_CHANGES.rst, vector/src/main/java/im/vector/push/PushManager.java
=> Crash: java.lang.StackOverflowError (PushManager.registerToThirdPartyServerRecursive)

vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java
=> Public room creation: improve UI for agent.agent users

TCHAP_CHANGES.rst, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/util/PreferencesManager.java
=> [FDroid] Prompt the user about the Battery optim if this is not already done

TCHAP_CHANGES.rst, vector/src/main/java/fr/gouv/tchap/activity/TchapRoomCreationActivity.java, vector/src/main/java/fr/gouv/tchap/fragments/TchapFavouriteMessagesFragment.kt, vector/src/main/java/fr/gouv/tchap/sdk/session/room/model/RoomRetention.kt, vector/src/main/java/fr/gouv/tchap/util/DinumUtils.kt, vector/src/main/java/im/vector/activity/VectorHomeActivity.java, vector/src/main/java/im/vector/activity/VectorRoomActivity.java, vector/src/main/java/im/vector/fragments/VectorRoomSettingsFragment.java, vector/src/main/java/im/vector/util/RoomUtils.java, vector/src/main/res/layout/activity_tchap_room_creation.xml
=> [Room retention] Support unlimited room history

vector/src/main/java/im/vector/VectorApp.java
=> Crash: isTaskCorrupted failed on java.lang.IllegalArgumentException

vector/src/main/java/im/vector/util/RoomUtils.java
The message was skip as soon as the retention period was undefined
=> Bug Fix Some last message are missing in the rooms list
